# Generated by Django 2.2 on 2019-04-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeRequestFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=20)),
                ('time_stamp', models.DateTimeField()),
                ('signal_strength', models.CharField(max_length=30)),
            ],
        ),
    ]
