# Generated by Django 2.2 on 2019-04-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_loc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteListRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('mac_address', models.CharField(max_length=18)),
            ],
        ),
        migrations.AlterField(
            model_name='proberequestframe',
            name='mac_address',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='proberequestframe',
            name='signal_strength',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='proberequestframe',
            name='time_stamp',
            field=models.CharField(max_length=25),
        ),
    ]
