# Generated by Django 2.2 on 2019-04-07 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf_loc', '0002_auto_20190406_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='proberequestframe',
            name='detector',
            field=models.CharField(default=datetime.time, max_length=30),
            preserve_default=False,
        ),
    ]
